### ISSUE TITLE
No speech was generated

### ISSUE THREAD

**Issue by korguchi** [r9y9/nnmnkwii_gallery#3]
Thank you for your many responses. I have found another issue and report it.
The process progressed smoothly, and it finally entered the stage of outputting sound.
However, no speech was output in [29].

https://gist.github.com/KORGUCHI/a82927ceb5dbdfa5e7b7aa01701986a7

**Comment by r9y9** [comment]
Seems there's no error. Have you checked if samples exist in `generated` directory?

**Comment by r9y9** [comment]
I'm wondering ` IPython.display.display` is not working correctly.

**Comment by r9y9** [comment]
Umm, I missed your comment at https://github.com/r9y9/nnmnkwii_gallery/issues/2#issuecomment-399639418. That's weird. 

```
test_label_paths = sorted(glob(join(DATA_ROOT, "test_label_phone_align", "*.lab")))
hts_generated_wav_files = sorted(glob(join("./generated/hts_nit_atr503_2mix/*.wav")))
```

Please inspect the above variables at the last cell in the notebook to check if we have test inputs.

**Comment by korguchi** [comment]
I found that there were no wav files in ./generated/hts_nit_atr503_2mix, so after giving the filenames into hts_generated_wav_files, it outputted the speeches.
I'm sorry for my trivial mistake and appreciate your help.

**Comment by r9y9** [comment]
Ah sorry. That's my fault. I haven't pushed the directory to the repo. I will do that immediately.

**Comment by r9y9** [comment]
Fixed.

**Comment by korguchi** [comment]
I can confirm it has been fixed and get the same result of the default. Thanks a lot.
