### ISSUE TITLE
Feature extraction file error

### ISSUE THREAD

**Issue by venkat-kittu** [r9y9/nnmnkwii_gallery#4]
I am running  command as "python scripts\prepare_features.py data"

C:\Program Files\Python36\lib\site-packages\nnmnkwii\datasets\__init__.py:125: UserWarning: No files are collected. You might have specified wrong data source.
  warn("No files are collected. You might have specified wrong data source.")
dataroot E:\python\speech_generation\nnmnkwii_gallery\data\questions-radio_dnn_416.hed
Traceback (most recent call last):
  File "scripts\prepare_features.py", line 190, in <module>
    Y_acoustic = FileSourceDataset(Y_acoustic_source)
  File "C:\Program Files\Python36\lib\site-packages\nnmnkwii\datasets\__init__.py", line 117, in __init__
    if not (lengths == lengths[0]).all():
IndexError: index 0 is out of bounds for axis 0 with size 0

Please tell me solution
Thanks in advance

**Comment by caopan16** [comment]
hi, I met the same problem as you when I was running tts_demo. I want to know how you solved it. Thanks.
