### ISSUE TITLE
IndexError: index 1886 is out of bounds for axis 0 with size 1846

### ISSUE THREAD

**Issue by markyouyuren** [r9y9/nnmnkwii_gallery#9]
I'm exploring nnmnkwii for singing synthesis.However, I encountered a problem that I could not solve by myself. I would like to ask for your help.
         My questions are as follows:
         In acoustic feature extraction,the Acoustic linguistic feature dim is (1899, 11349),when the Acoustic feature dim is (1846, 187),This problem caused errors in the training of acoustic models.Error message:
![image](https://user-images.githubusercontent.com/34672671/58857456-e899e080-86d7-11e9-8b85-7cb8b63ef498.png)
![image](https://user-images.githubusercontent.com/34672671/58857481-f6e7fc80-86d7-11e9-81c1-4283c3737176.png)

**Comment by markyouyuren** [comment]
I don't know how to solve this problem

**Comment by r9y9** [comment]
Please describe steps to reproduce and what you are trying to do in details, otherwise it's hard to help.

**Comment by markyouyuren** [comment]
I use DNN-based statistical speech synthesis (en),

![image](https://user-images.githubusercontent.com/34672671/58858758-db322580-86da-11e9-9e32-8c5683a5728a.png)

This is my Data specification.The speech sampling rate is 16000,but The problem set has more than 10,000 rows.  My labels are use_phone_aligned
